"""updated doctor model

Revision ID: 215f65d79dde
Revises: 516f6ba10073
Create Date: 2025-01-04 15:23:38.932384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215f65d79dde'
down_revision = '516f6ba10073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
