"""updated doctor model

Revision ID: 516f6ba10073
Revises: 190787152cb0
Create Date: 2025-01-04 15:15:44.834180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516f6ba10073'
down_revision = '190787152cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
