name: CI Workflow

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, edited, reopened]

permissions:
  contents: read

jobs:
  build-service:
    name: Patient Simulator Service build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.0

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run pytest --cov=app --cov-report xml
        continue-on-error: false

#      - name: SonarQube scan
#        uses: sonarsource/sonarqube-scan-action@master
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}